// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/distributorbinding"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DistributorBindingUpdate is the builder for updating DistributorBinding entities.
type DistributorBindingUpdate struct {
	config
	hooks    []Hook
	mutation *DistributorBindingMutation
}

// Where appends a list predicates to the DistributorBindingUpdate builder.
func (_u *DistributorBindingUpdate) Where(ps ...predicate.DistributorBinding) *DistributorBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDistributorID sets the "distributor_id" field.
func (_u *DistributorBindingUpdate) SetDistributorID(v string) *DistributorBindingUpdate {
	_u.mutation.SetDistributorID(v)
	return _u
}

// SetNillableDistributorID sets the "distributor_id" field if the given value is not nil.
func (_u *DistributorBindingUpdate) SetNillableDistributorID(v *string) *DistributorBindingUpdate {
	if v != nil {
		_u.SetDistributorID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DistributorBindingUpdate) SetName(v string) *DistributorBindingUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DistributorBindingUpdate) SetNillableName(v *string) *DistributorBindingUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *DistributorBindingUpdate) SetTokenHash(v string) *DistributorBindingUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *DistributorBindingUpdate) SetNillableTokenHash(v *string) *DistributorBindingUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DistributorBindingUpdate) SetEnabled(v bool) *DistributorBindingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DistributorBindingUpdate) SetNillableEnabled(v *bool) *DistributorBindingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *DistributorBindingUpdate) SetContactEmail(v string) *DistributorBindingUpdate {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *DistributorBindingUpdate) SetNillableContactEmail(v *string) *DistributorBindingUpdate {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *DistributorBindingUpdate) ClearContactEmail() *DistributorBindingUpdate {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *DistributorBindingUpdate) SetNotes(v string) *DistributorBindingUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *DistributorBindingUpdate) SetNillableNotes(v *string) *DistributorBindingUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *DistributorBindingUpdate) ClearNotes() *DistributorBindingUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DistributorBindingUpdate) SetExpiresAt(v time.Time) *DistributorBindingUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DistributorBindingUpdate) SetNillableExpiresAt(v *time.Time) *DistributorBindingUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *DistributorBindingUpdate) ClearExpiresAt() *DistributorBindingUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DistributorBindingUpdate) SetUpdatedAt(v time.Time) *DistributorBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DistributorBindingMutation object of the builder.
func (_u *DistributorBindingUpdate) Mutation() *DistributorBindingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DistributorBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DistributorBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DistributorBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DistributorBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DistributorBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := distributorbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DistributorBindingUpdate) check() error {
	if v, ok := _u.mutation.DistributorID(); ok {
		if err := distributorbinding.DistributorIDValidator(v); err != nil {
			return &ValidationError{Name: "distributor_id", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.distributor_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := distributorbinding.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := distributorbinding.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactEmail(); ok {
		if err := distributorbinding.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.contact_email": %w`, err)}
		}
	}
	return nil
}

func (_u *DistributorBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(distributorbinding.Table, distributorbinding.Columns, sqlgraph.NewFieldSpec(distributorbinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DistributorID(); ok {
		_spec.SetField(distributorbinding.FieldDistributorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(distributorbinding.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(distributorbinding.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(distributorbinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(distributorbinding.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(distributorbinding.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(distributorbinding.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(distributorbinding.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(distributorbinding.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(distributorbinding.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(distributorbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{distributorbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DistributorBindingUpdateOne is the builder for updating a single DistributorBinding entity.
type DistributorBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DistributorBindingMutation
}

// SetDistributorID sets the "distributor_id" field.
func (_u *DistributorBindingUpdateOne) SetDistributorID(v string) *DistributorBindingUpdateOne {
	_u.mutation.SetDistributorID(v)
	return _u
}

// SetNillableDistributorID sets the "distributor_id" field if the given value is not nil.
func (_u *DistributorBindingUpdateOne) SetNillableDistributorID(v *string) *DistributorBindingUpdateOne {
	if v != nil {
		_u.SetDistributorID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DistributorBindingUpdateOne) SetName(v string) *DistributorBindingUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DistributorBindingUpdateOne) SetNillableName(v *string) *DistributorBindingUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *DistributorBindingUpdateOne) SetTokenHash(v string) *DistributorBindingUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *DistributorBindingUpdateOne) SetNillableTokenHash(v *string) *DistributorBindingUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DistributorBindingUpdateOne) SetEnabled(v bool) *DistributorBindingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DistributorBindingUpdateOne) SetNillableEnabled(v *bool) *DistributorBindingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *DistributorBindingUpdateOne) SetContactEmail(v string) *DistributorBindingUpdateOne {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *DistributorBindingUpdateOne) SetNillableContactEmail(v *string) *DistributorBindingUpdateOne {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *DistributorBindingUpdateOne) ClearContactEmail() *DistributorBindingUpdateOne {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *DistributorBindingUpdateOne) SetNotes(v string) *DistributorBindingUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *DistributorBindingUpdateOne) SetNillableNotes(v *string) *DistributorBindingUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *DistributorBindingUpdateOne) ClearNotes() *DistributorBindingUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DistributorBindingUpdateOne) SetExpiresAt(v time.Time) *DistributorBindingUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DistributorBindingUpdateOne) SetNillableExpiresAt(v *time.Time) *DistributorBindingUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *DistributorBindingUpdateOne) ClearExpiresAt() *DistributorBindingUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DistributorBindingUpdateOne) SetUpdatedAt(v time.Time) *DistributorBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DistributorBindingMutation object of the builder.
func (_u *DistributorBindingUpdateOne) Mutation() *DistributorBindingMutation {
	return _u.mutation
}

// Where appends a list predicates to the DistributorBindingUpdate builder.
func (_u *DistributorBindingUpdateOne) Where(ps ...predicate.DistributorBinding) *DistributorBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DistributorBindingUpdateOne) Select(field string, fields ...string) *DistributorBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DistributorBinding entity.
func (_u *DistributorBindingUpdateOne) Save(ctx context.Context) (*DistributorBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DistributorBindingUpdateOne) SaveX(ctx context.Context) *DistributorBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DistributorBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DistributorBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DistributorBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := distributorbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DistributorBindingUpdateOne) check() error {
	if v, ok := _u.mutation.DistributorID(); ok {
		if err := distributorbinding.DistributorIDValidator(v); err != nil {
			return &ValidationError{Name: "distributor_id", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.distributor_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := distributorbinding.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := distributorbinding.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactEmail(); ok {
		if err := distributorbinding.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.contact_email": %w`, err)}
		}
	}
	return nil
}

func (_u *DistributorBindingUpdateOne) sqlSave(ctx context.Context) (_node *DistributorBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(distributorbinding.Table, distributorbinding.Columns, sqlgraph.NewFieldSpec(distributorbinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DistributorBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, distributorbinding.FieldID)
		for _, f := range fields {
			if !distributorbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != distributorbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DistributorID(); ok {
		_spec.SetField(distributorbinding.FieldDistributorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(distributorbinding.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(distributorbinding.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(distributorbinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(distributorbinding.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(distributorbinding.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(distributorbinding.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(distributorbinding.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(distributorbinding.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(distributorbinding.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(distributorbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DistributorBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{distributorbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
