// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/distributorbinding"
)

// DistributorBindingCreate is the builder for creating a DistributorBinding entity.
type DistributorBindingCreate struct {
	config
	mutation *DistributorBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDistributorID sets the "distributor_id" field.
func (_c *DistributorBindingCreate) SetDistributorID(v string) *DistributorBindingCreate {
	_c.mutation.SetDistributorID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DistributorBindingCreate) SetName(v string) *DistributorBindingCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *DistributorBindingCreate) SetTokenHash(v string) *DistributorBindingCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *DistributorBindingCreate) SetEnabled(v bool) *DistributorBindingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *DistributorBindingCreate) SetNillableEnabled(v *bool) *DistributorBindingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetContactEmail sets the "contact_email" field.
func (_c *DistributorBindingCreate) SetContactEmail(v string) *DistributorBindingCreate {
	_c.mutation.SetContactEmail(v)
	return _c
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_c *DistributorBindingCreate) SetNillableContactEmail(v *string) *DistributorBindingCreate {
	if v != nil {
		_c.SetContactEmail(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *DistributorBindingCreate) SetNotes(v string) *DistributorBindingCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *DistributorBindingCreate) SetNillableNotes(v *string) *DistributorBindingCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *DistributorBindingCreate) SetExpiresAt(v time.Time) *DistributorBindingCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *DistributorBindingCreate) SetNillableExpiresAt(v *time.Time) *DistributorBindingCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DistributorBindingCreate) SetCreatedAt(v time.Time) *DistributorBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DistributorBindingCreate) SetNillableCreatedAt(v *time.Time) *DistributorBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DistributorBindingCreate) SetUpdatedAt(v time.Time) *DistributorBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DistributorBindingCreate) SetNillableUpdatedAt(v *time.Time) *DistributorBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DistributorBindingMutation object of the builder.
func (_c *DistributorBindingCreate) Mutation() *DistributorBindingMutation {
	return _c.mutation
}

// Save creates the DistributorBinding in the database.
func (_c *DistributorBindingCreate) Save(ctx context.Context) (*DistributorBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DistributorBindingCreate) SaveX(ctx context.Context) *DistributorBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DistributorBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DistributorBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DistributorBindingCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := distributorbinding.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := distributorbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := distributorbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DistributorBindingCreate) check() error {
	if _, ok := _c.mutation.DistributorID(); !ok {
		return &ValidationError{Name: "distributor_id", err: errors.New(`ent: missing required field "DistributorBinding.distributor_id"`)}
	}
	if v, ok := _c.mutation.DistributorID(); ok {
		if err := distributorbinding.DistributorIDValidator(v); err != nil {
			return &ValidationError{Name: "distributor_id", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.distributor_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DistributorBinding.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := distributorbinding.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "DistributorBinding.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := distributorbinding.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "DistributorBinding.enabled"`)}
	}
	if v, ok := _c.mutation.ContactEmail(); ok {
		if err := distributorbinding.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "DistributorBinding.contact_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DistributorBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DistributorBinding.updated_at"`)}
	}
	return nil
}

func (_c *DistributorBindingCreate) sqlSave(ctx context.Context) (*DistributorBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DistributorBindingCreate) createSpec() (*DistributorBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &DistributorBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(distributorbinding.Table, sqlgraph.NewFieldSpec(distributorbinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.DistributorID(); ok {
		_spec.SetField(distributorbinding.FieldDistributorID, field.TypeString, value)
		_node.DistributorID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(distributorbinding.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(distributorbinding.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(distributorbinding.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.ContactEmail(); ok {
		_spec.SetField(distributorbinding.FieldContactEmail, field.TypeString, value)
		_node.ContactEmail = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(distributorbinding.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(distributorbinding.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(distributorbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(distributorbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DistributorBinding.Create().
//		SetDistributorID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DistributorBindingUpsert) {
//			SetDistributorID(v+v).
//		}).
//		Exec(ctx)
func (_c *DistributorBindingCreate) OnConflict(opts ...sql.ConflictOption) *DistributorBindingUpsertOne {
	_c.conflict = opts
	return &DistributorBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DistributorBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DistributorBindingCreate) OnConflictColumns(columns ...string) *DistributorBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DistributorBindingUpsertOne{
		create: _c,
	}
}

type (
	// DistributorBindingUpsertOne is the builder for "upsert"-ing
	//  one DistributorBinding node.
	DistributorBindingUpsertOne struct {
		create *DistributorBindingCreate
	}

	// DistributorBindingUpsert is the "OnConflict" setter.
	DistributorBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetDistributorID sets the "distributor_id" field.
func (u *DistributorBindingUpsert) SetDistributorID(v string) *DistributorBindingUpsert {
	u.Set(distributorbinding.FieldDistributorID, v)
	return u
}

// UpdateDistributorID sets the "distributor_id" field to the value that was provided on create.
func (u *DistributorBindingUpsert) UpdateDistributorID() *DistributorBindingUpsert {
	u.SetExcluded(distributorbinding.FieldDistributorID)
	return u
}

// SetName sets the "name" field.
func (u *DistributorBindingUpsert) SetName(v string) *DistributorBindingUpsert {
	u.Set(distributorbinding.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DistributorBindingUpsert) UpdateName() *DistributorBindingUpsert {
	u.SetExcluded(distributorbinding.FieldName)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *DistributorBindingUpsert) SetTokenHash(v string) *DistributorBindingUpsert {
	u.Set(distributorbinding.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *DistributorBindingUpsert) UpdateTokenHash() *DistributorBindingUpsert {
	u.SetExcluded(distributorbinding.FieldTokenHash)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *DistributorBindingUpsert) SetEnabled(v bool) *DistributorBindingUpsert {
	u.Set(distributorbinding.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DistributorBindingUpsert) UpdateEnabled() *DistributorBindingUpsert {
	u.SetExcluded(distributorbinding.FieldEnabled)
	return u
}

// SetContactEmail sets the "contact_email" field.
func (u *DistributorBindingUpsert) SetContactEmail(v string) *DistributorBindingUpsert {
	u.Set(distributorbinding.FieldContactEmail, v)
	return u
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *DistributorBindingUpsert) UpdateContactEmail() *DistributorBindingUpsert {
	u.SetExcluded(distributorbinding.FieldContactEmail)
	return u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (u *DistributorBindingUpsert) ClearContactEmail() *DistributorBindingUpsert {
	u.SetNull(distributorbinding.FieldContactEmail)
	return u
}

// SetNotes sets the "notes" field.
func (u *DistributorBindingUpsert) SetNotes(v string) *DistributorBindingUpsert {
	u.Set(distributorbinding.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *DistributorBindingUpsert) UpdateNotes() *DistributorBindingUpsert {
	u.SetExcluded(distributorbinding.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *DistributorBindingUpsert) ClearNotes() *DistributorBindingUpsert {
	u.SetNull(distributorbinding.FieldNotes)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *DistributorBindingUpsert) SetExpiresAt(v time.Time) *DistributorBindingUpsert {
	u.Set(distributorbinding.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DistributorBindingUpsert) UpdateExpiresAt() *DistributorBindingUpsert {
	u.SetExcluded(distributorbinding.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *DistributorBindingUpsert) ClearExpiresAt() *DistributorBindingUpsert {
	u.SetNull(distributorbinding.FieldExpiresAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DistributorBindingUpsert) SetUpdatedAt(v time.Time) *DistributorBindingUpsert {
	u.Set(distributorbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DistributorBindingUpsert) UpdateUpdatedAt() *DistributorBindingUpsert {
	u.SetExcluded(distributorbinding.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DistributorBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DistributorBindingUpsertOne) UpdateNewValues() *DistributorBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(distributorbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DistributorBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DistributorBindingUpsertOne) Ignore() *DistributorBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DistributorBindingUpsertOne) DoNothing() *DistributorBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DistributorBindingCreate.OnConflict
// documentation for more info.
func (u *DistributorBindingUpsertOne) Update(set func(*DistributorBindingUpsert)) *DistributorBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DistributorBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetDistributorID sets the "distributor_id" field.
func (u *DistributorBindingUpsertOne) SetDistributorID(v string) *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetDistributorID(v)
	})
}

// UpdateDistributorID sets the "distributor_id" field to the value that was provided on create.
func (u *DistributorBindingUpsertOne) UpdateDistributorID() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateDistributorID()
	})
}

// SetName sets the "name" field.
func (u *DistributorBindingUpsertOne) SetName(v string) *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DistributorBindingUpsertOne) UpdateName() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateName()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *DistributorBindingUpsertOne) SetTokenHash(v string) *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *DistributorBindingUpsertOne) UpdateTokenHash() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateTokenHash()
	})
}

// SetEnabled sets the "enabled" field.
func (u *DistributorBindingUpsertOne) SetEnabled(v bool) *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DistributorBindingUpsertOne) UpdateEnabled() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateEnabled()
	})
}

// SetContactEmail sets the "contact_email" field.
func (u *DistributorBindingUpsertOne) SetContactEmail(v string) *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetContactEmail(v)
	})
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *DistributorBindingUpsertOne) UpdateContactEmail() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateContactEmail()
	})
}

// ClearContactEmail clears the value of the "contact_email" field.
func (u *DistributorBindingUpsertOne) ClearContactEmail() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.ClearContactEmail()
	})
}

// SetNotes sets the "notes" field.
func (u *DistributorBindingUpsertOne) SetNotes(v string) *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *DistributorBindingUpsertOne) UpdateNotes() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *DistributorBindingUpsertOne) ClearNotes() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.ClearNotes()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DistributorBindingUpsertOne) SetExpiresAt(v time.Time) *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DistributorBindingUpsertOne) UpdateExpiresAt() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *DistributorBindingUpsertOne) ClearExpiresAt() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.ClearExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DistributorBindingUpsertOne) SetUpdatedAt(v time.Time) *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DistributorBindingUpsertOne) UpdateUpdatedAt() *DistributorBindingUpsertOne {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DistributorBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DistributorBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DistributorBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DistributorBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DistributorBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DistributorBindingCreateBulk is the builder for creating many DistributorBinding entities in bulk.
type DistributorBindingCreateBulk struct {
	config
	err      error
	builders []*DistributorBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the DistributorBinding entities in the database.
func (_c *DistributorBindingCreateBulk) Save(ctx context.Context) ([]*DistributorBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DistributorBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DistributorBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DistributorBindingCreateBulk) SaveX(ctx context.Context) []*DistributorBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DistributorBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DistributorBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DistributorBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DistributorBindingUpsert) {
//			SetDistributorID(v+v).
//		}).
//		Exec(ctx)
func (_c *DistributorBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *DistributorBindingUpsertBulk {
	_c.conflict = opts
	return &DistributorBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DistributorBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DistributorBindingCreateBulk) OnConflictColumns(columns ...string) *DistributorBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DistributorBindingUpsertBulk{
		create: _c,
	}
}

// DistributorBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of DistributorBinding nodes.
type DistributorBindingUpsertBulk struct {
	create *DistributorBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DistributorBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DistributorBindingUpsertBulk) UpdateNewValues() *DistributorBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(distributorbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DistributorBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DistributorBindingUpsertBulk) Ignore() *DistributorBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DistributorBindingUpsertBulk) DoNothing() *DistributorBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DistributorBindingCreateBulk.OnConflict
// documentation for more info.
func (u *DistributorBindingUpsertBulk) Update(set func(*DistributorBindingUpsert)) *DistributorBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DistributorBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetDistributorID sets the "distributor_id" field.
func (u *DistributorBindingUpsertBulk) SetDistributorID(v string) *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetDistributorID(v)
	})
}

// UpdateDistributorID sets the "distributor_id" field to the value that was provided on create.
func (u *DistributorBindingUpsertBulk) UpdateDistributorID() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateDistributorID()
	})
}

// SetName sets the "name" field.
func (u *DistributorBindingUpsertBulk) SetName(v string) *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DistributorBindingUpsertBulk) UpdateName() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateName()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *DistributorBindingUpsertBulk) SetTokenHash(v string) *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *DistributorBindingUpsertBulk) UpdateTokenHash() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateTokenHash()
	})
}

// SetEnabled sets the "enabled" field.
func (u *DistributorBindingUpsertBulk) SetEnabled(v bool) *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DistributorBindingUpsertBulk) UpdateEnabled() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateEnabled()
	})
}

// SetContactEmail sets the "contact_email" field.
func (u *DistributorBindingUpsertBulk) SetContactEmail(v string) *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetContactEmail(v)
	})
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *DistributorBindingUpsertBulk) UpdateContactEmail() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateContactEmail()
	})
}

// ClearContactEmail clears the value of the "contact_email" field.
func (u *DistributorBindingUpsertBulk) ClearContactEmail() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.ClearContactEmail()
	})
}

// SetNotes sets the "notes" field.
func (u *DistributorBindingUpsertBulk) SetNotes(v string) *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *DistributorBindingUpsertBulk) UpdateNotes() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *DistributorBindingUpsertBulk) ClearNotes() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.ClearNotes()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DistributorBindingUpsertBulk) SetExpiresAt(v time.Time) *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DistributorBindingUpsertBulk) UpdateExpiresAt() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *DistributorBindingUpsertBulk) ClearExpiresAt() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.ClearExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DistributorBindingUpsertBulk) SetUpdatedAt(v time.Time) *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DistributorBindingUpsertBulk) UpdateUpdatedAt() *DistributorBindingUpsertBulk {
	return u.Update(func(s *DistributorBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DistributorBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DistributorBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DistributorBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DistributorBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
