// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/distributorbinding"
)

// DistributorBinding is the model entity for the DistributorBinding schema.
type DistributorBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 外部 distributor_id（站新侧标识，如 'site'）
	DistributorID string `json:"distributor_id,omitempty"`
	// 分销商名称（用于后台显示）
	Name string `json:"name,omitempty"`
	// SHA-256(token) 用于查询；token 明文仅展示一次
	TokenHash string `json:"token_hash,omitempty"`
	// false 时拒绝请求
	Enabled bool `json:"enabled,omitempty"`
	// ContactEmail holds the value of the "contact_email" field.
	ContactEmail *string `json:"contact_email,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DistributorBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case distributorbinding.FieldEnabled:
			values[i] = new(sql.NullBool)
		case distributorbinding.FieldID:
			values[i] = new(sql.NullInt64)
		case distributorbinding.FieldDistributorID, distributorbinding.FieldName, distributorbinding.FieldTokenHash, distributorbinding.FieldContactEmail, distributorbinding.FieldNotes:
			values[i] = new(sql.NullString)
		case distributorbinding.FieldExpiresAt, distributorbinding.FieldCreatedAt, distributorbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DistributorBinding fields.
func (_m *DistributorBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case distributorbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case distributorbinding.FieldDistributorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field distributor_id", values[i])
			} else if value.Valid {
				_m.DistributorID = value.String
			}
		case distributorbinding.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case distributorbinding.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case distributorbinding.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case distributorbinding.FieldContactEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_email", values[i])
			} else if value.Valid {
				_m.ContactEmail = new(string)
				*_m.ContactEmail = value.String
			}
		case distributorbinding.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case distributorbinding.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case distributorbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case distributorbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DistributorBinding.
// This includes values selected through modifiers, order, etc.
func (_m *DistributorBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DistributorBinding.
// Note that you need to call DistributorBinding.Unwrap() before calling this method if this DistributorBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DistributorBinding) Update() *DistributorBindingUpdateOne {
	return NewDistributorBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DistributorBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DistributorBinding) Unwrap() *DistributorBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DistributorBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DistributorBinding) String() string {
	var builder strings.Builder
	builder.WriteString("DistributorBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("distributor_id=")
	builder.WriteString(_m.DistributorID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.ContactEmail; v != nil {
		builder.WriteString("contact_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DistributorBindings is a parsable slice of DistributorBinding.
type DistributorBindings []*DistributorBinding
