// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/userapikey"
)

// UserAPIKeyUpdate is the builder for updating UserAPIKey entities.
type UserAPIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *UserAPIKeyMutation
}

// Where appends a list predicates to the UserAPIKeyUpdate builder.
func (_u *UserAPIKeyUpdate) Where(ps ...predicate.UserAPIKey) *UserAPIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAPIKeyUpdate) SetUserID(v int64) *UserAPIKeyUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableUserID(v *int64) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAPIKeyUpdate) AddUserID(v int64) *UserAPIKeyUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserAPIKeyUpdate) SetGroupID(v int64) *UserAPIKeyUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableGroupID(v *int64) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserAPIKeyUpdate) AddGroupID(v int64) *UserAPIKeyUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *UserAPIKeyUpdate) SetKeyHash(v string) *UserAPIKeyUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableKeyHash(v *string) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (_u *UserAPIKeyUpdate) SetKeyEncrypted(v string) *UserAPIKeyUpdate {
	_u.mutation.SetKeyEncrypted(v)
	return _u
}

// SetNillableKeyEncrypted sets the "key_encrypted" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableKeyEncrypted(v *string) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetKeyEncrypted(*v)
	}
	return _u
}

// ClearKeyEncrypted clears the value of the "key_encrypted" field.
func (_u *UserAPIKeyUpdate) ClearKeyEncrypted() *UserAPIKeyUpdate {
	_u.mutation.ClearKeyEncrypted()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserAPIKeyUpdate) SetStatus(v string) *UserAPIKeyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableStatus(v *string) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIssuedBy sets the "issued_by" field.
func (_u *UserAPIKeyUpdate) SetIssuedBy(v string) *UserAPIKeyUpdate {
	_u.mutation.SetIssuedBy(v)
	return _u
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableIssuedBy(v *string) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetIssuedBy(*v)
	}
	return _u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (_u *UserAPIKeyUpdate) ClearIssuedBy() *UserAPIKeyUpdate {
	_u.mutation.ClearIssuedBy()
	return _u
}

// SetIssuedByID sets the "issued_by_id" field.
func (_u *UserAPIKeyUpdate) SetIssuedByID(v string) *UserAPIKeyUpdate {
	_u.mutation.SetIssuedByID(v)
	return _u
}

// SetNillableIssuedByID sets the "issued_by_id" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableIssuedByID(v *string) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetIssuedByID(*v)
	}
	return _u
}

// ClearIssuedByID clears the value of the "issued_by_id" field.
func (_u *UserAPIKeyUpdate) ClearIssuedByID() *UserAPIKeyUpdate {
	_u.mutation.ClearIssuedByID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserAPIKeyUpdate) SetExpiresAt(v time.Time) *UserAPIKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableExpiresAt(v *time.Time) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserAPIKeyUpdate) ClearExpiresAt() *UserAPIKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *UserAPIKeyUpdate) SetLastUsedAt(v time.Time) *UserAPIKeyUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableLastUsedAt(v *time.Time) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *UserAPIKeyUpdate) ClearLastUsedAt() *UserAPIKeyUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserAPIKeyUpdate) SetNotes(v string) *UserAPIKeyUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserAPIKeyUpdate) SetNillableNotes(v *string) *UserAPIKeyUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserAPIKeyUpdate) ClearNotes() *UserAPIKeyUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAPIKeyUpdate) SetUpdatedAt(v time.Time) *UserAPIKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserAPIKeyMutation object of the builder.
func (_u *UserAPIKeyUpdate) Mutation() *UserAPIKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAPIKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAPIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAPIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAPIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAPIKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAPIKeyUpdate) check() error {
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := userapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userapikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedBy(); ok {
		if err := userapikey.IssuedByValidator(v); err != nil {
			return &ValidationError{Name: "issued_by", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.issued_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedByID(); ok {
		if err := userapikey.IssuedByIDValidator(v); err != nil {
			return &ValidationError{Name: "issued_by_id", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.issued_by_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAPIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userapikey.Table, userapikey.Columns, sqlgraph.NewFieldSpec(userapikey.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userapikey.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userapikey.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(userapikey.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(userapikey.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(userapikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyEncrypted(); ok {
		_spec.SetField(userapikey.FieldKeyEncrypted, field.TypeString, value)
	}
	if _u.mutation.KeyEncryptedCleared() {
		_spec.ClearField(userapikey.FieldKeyEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userapikey.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedBy(); ok {
		_spec.SetField(userapikey.FieldIssuedBy, field.TypeString, value)
	}
	if _u.mutation.IssuedByCleared() {
		_spec.ClearField(userapikey.FieldIssuedBy, field.TypeString)
	}
	if value, ok := _u.mutation.IssuedByID(); ok {
		_spec.SetField(userapikey.FieldIssuedByID, field.TypeString, value)
	}
	if _u.mutation.IssuedByIDCleared() {
		_spec.ClearField(userapikey.FieldIssuedByID, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(userapikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(userapikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userapikey.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(userapikey.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAPIKeyUpdateOne is the builder for updating a single UserAPIKey entity.
type UserAPIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAPIKeyMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserAPIKeyUpdateOne) SetUserID(v int64) *UserAPIKeyUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableUserID(v *int64) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAPIKeyUpdateOne) AddUserID(v int64) *UserAPIKeyUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserAPIKeyUpdateOne) SetGroupID(v int64) *UserAPIKeyUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableGroupID(v *int64) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserAPIKeyUpdateOne) AddGroupID(v int64) *UserAPIKeyUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *UserAPIKeyUpdateOne) SetKeyHash(v string) *UserAPIKeyUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableKeyHash(v *string) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (_u *UserAPIKeyUpdateOne) SetKeyEncrypted(v string) *UserAPIKeyUpdateOne {
	_u.mutation.SetKeyEncrypted(v)
	return _u
}

// SetNillableKeyEncrypted sets the "key_encrypted" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableKeyEncrypted(v *string) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetKeyEncrypted(*v)
	}
	return _u
}

// ClearKeyEncrypted clears the value of the "key_encrypted" field.
func (_u *UserAPIKeyUpdateOne) ClearKeyEncrypted() *UserAPIKeyUpdateOne {
	_u.mutation.ClearKeyEncrypted()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserAPIKeyUpdateOne) SetStatus(v string) *UserAPIKeyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableStatus(v *string) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIssuedBy sets the "issued_by" field.
func (_u *UserAPIKeyUpdateOne) SetIssuedBy(v string) *UserAPIKeyUpdateOne {
	_u.mutation.SetIssuedBy(v)
	return _u
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableIssuedBy(v *string) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetIssuedBy(*v)
	}
	return _u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (_u *UserAPIKeyUpdateOne) ClearIssuedBy() *UserAPIKeyUpdateOne {
	_u.mutation.ClearIssuedBy()
	return _u
}

// SetIssuedByID sets the "issued_by_id" field.
func (_u *UserAPIKeyUpdateOne) SetIssuedByID(v string) *UserAPIKeyUpdateOne {
	_u.mutation.SetIssuedByID(v)
	return _u
}

// SetNillableIssuedByID sets the "issued_by_id" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableIssuedByID(v *string) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetIssuedByID(*v)
	}
	return _u
}

// ClearIssuedByID clears the value of the "issued_by_id" field.
func (_u *UserAPIKeyUpdateOne) ClearIssuedByID() *UserAPIKeyUpdateOne {
	_u.mutation.ClearIssuedByID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserAPIKeyUpdateOne) SetExpiresAt(v time.Time) *UserAPIKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserAPIKeyUpdateOne) ClearExpiresAt() *UserAPIKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *UserAPIKeyUpdateOne) SetLastUsedAt(v time.Time) *UserAPIKeyUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableLastUsedAt(v *time.Time) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *UserAPIKeyUpdateOne) ClearLastUsedAt() *UserAPIKeyUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserAPIKeyUpdateOne) SetNotes(v string) *UserAPIKeyUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserAPIKeyUpdateOne) SetNillableNotes(v *string) *UserAPIKeyUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserAPIKeyUpdateOne) ClearNotes() *UserAPIKeyUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAPIKeyUpdateOne) SetUpdatedAt(v time.Time) *UserAPIKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserAPIKeyMutation object of the builder.
func (_u *UserAPIKeyUpdateOne) Mutation() *UserAPIKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAPIKeyUpdate builder.
func (_u *UserAPIKeyUpdateOne) Where(ps ...predicate.UserAPIKey) *UserAPIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAPIKeyUpdateOne) Select(field string, fields ...string) *UserAPIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAPIKey entity.
func (_u *UserAPIKeyUpdateOne) Save(ctx context.Context) (*UserAPIKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAPIKeyUpdateOne) SaveX(ctx context.Context) *UserAPIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAPIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAPIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAPIKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAPIKeyUpdateOne) check() error {
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := userapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userapikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedBy(); ok {
		if err := userapikey.IssuedByValidator(v); err != nil {
			return &ValidationError{Name: "issued_by", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.issued_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedByID(); ok {
		if err := userapikey.IssuedByIDValidator(v); err != nil {
			return &ValidationError{Name: "issued_by_id", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.issued_by_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAPIKeyUpdateOne) sqlSave(ctx context.Context) (_node *UserAPIKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userapikey.Table, userapikey.Columns, sqlgraph.NewFieldSpec(userapikey.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAPIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userapikey.FieldID)
		for _, f := range fields {
			if !userapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userapikey.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userapikey.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(userapikey.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(userapikey.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(userapikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyEncrypted(); ok {
		_spec.SetField(userapikey.FieldKeyEncrypted, field.TypeString, value)
	}
	if _u.mutation.KeyEncryptedCleared() {
		_spec.ClearField(userapikey.FieldKeyEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userapikey.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedBy(); ok {
		_spec.SetField(userapikey.FieldIssuedBy, field.TypeString, value)
	}
	if _u.mutation.IssuedByCleared() {
		_spec.ClearField(userapikey.FieldIssuedBy, field.TypeString)
	}
	if value, ok := _u.mutation.IssuedByID(); ok {
		_spec.SetField(userapikey.FieldIssuedByID, field.TypeString, value)
	}
	if _u.mutation.IssuedByIDCleared() {
		_spec.ClearField(userapikey.FieldIssuedByID, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(userapikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(userapikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userapikey.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(userapikey.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserAPIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
