// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/userapikey"
)

// UserAPIKeyCreate is the builder for creating a UserAPIKey entity.
type UserAPIKeyCreate struct {
	config
	mutation *UserAPIKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserAPIKeyCreate) SetUserID(v int64) *UserAPIKeyCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UserAPIKeyCreate) SetGroupID(v int64) *UserAPIKeyCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *UserAPIKeyCreate) SetKeyHash(v string) *UserAPIKeyCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (_c *UserAPIKeyCreate) SetKeyEncrypted(v string) *UserAPIKeyCreate {
	_c.mutation.SetKeyEncrypted(v)
	return _c
}

// SetNillableKeyEncrypted sets the "key_encrypted" field if the given value is not nil.
func (_c *UserAPIKeyCreate) SetNillableKeyEncrypted(v *string) *UserAPIKeyCreate {
	if v != nil {
		_c.SetKeyEncrypted(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserAPIKeyCreate) SetStatus(v string) *UserAPIKeyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserAPIKeyCreate) SetNillableStatus(v *string) *UserAPIKeyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIssuedBy sets the "issued_by" field.
func (_c *UserAPIKeyCreate) SetIssuedBy(v string) *UserAPIKeyCreate {
	_c.mutation.SetIssuedBy(v)
	return _c
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_c *UserAPIKeyCreate) SetNillableIssuedBy(v *string) *UserAPIKeyCreate {
	if v != nil {
		_c.SetIssuedBy(*v)
	}
	return _c
}

// SetIssuedByID sets the "issued_by_id" field.
func (_c *UserAPIKeyCreate) SetIssuedByID(v string) *UserAPIKeyCreate {
	_c.mutation.SetIssuedByID(v)
	return _c
}

// SetNillableIssuedByID sets the "issued_by_id" field if the given value is not nil.
func (_c *UserAPIKeyCreate) SetNillableIssuedByID(v *string) *UserAPIKeyCreate {
	if v != nil {
		_c.SetIssuedByID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserAPIKeyCreate) SetExpiresAt(v time.Time) *UserAPIKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UserAPIKeyCreate) SetNillableExpiresAt(v *time.Time) *UserAPIKeyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *UserAPIKeyCreate) SetLastUsedAt(v time.Time) *UserAPIKeyCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *UserAPIKeyCreate) SetNillableLastUsedAt(v *time.Time) *UserAPIKeyCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *UserAPIKeyCreate) SetNotes(v string) *UserAPIKeyCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *UserAPIKeyCreate) SetNillableNotes(v *string) *UserAPIKeyCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAPIKeyCreate) SetCreatedAt(v time.Time) *UserAPIKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAPIKeyCreate) SetNillableCreatedAt(v *time.Time) *UserAPIKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAPIKeyCreate) SetUpdatedAt(v time.Time) *UserAPIKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAPIKeyCreate) SetNillableUpdatedAt(v *time.Time) *UserAPIKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UserAPIKeyMutation object of the builder.
func (_c *UserAPIKeyCreate) Mutation() *UserAPIKeyMutation {
	return _c.mutation
}

// Save creates the UserAPIKey in the database.
func (_c *UserAPIKeyCreate) Save(ctx context.Context) (*UserAPIKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAPIKeyCreate) SaveX(ctx context.Context) *UserAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAPIKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAPIKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAPIKeyCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := userapikey.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userapikey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userapikey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAPIKeyCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserAPIKey.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "UserAPIKey.group_id"`)}
	}
	if _, ok := _c.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "UserAPIKey.key_hash"`)}
	}
	if v, ok := _c.mutation.KeyHash(); ok {
		if err := userapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserAPIKey.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userapikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IssuedBy(); ok {
		if err := userapikey.IssuedByValidator(v); err != nil {
			return &ValidationError{Name: "issued_by", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.issued_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IssuedByID(); ok {
		if err := userapikey.IssuedByIDValidator(v); err != nil {
			return &ValidationError{Name: "issued_by_id", err: fmt.Errorf(`ent: validator failed for field "UserAPIKey.issued_by_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAPIKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAPIKey.updated_at"`)}
	}
	return nil
}

func (_c *UserAPIKeyCreate) sqlSave(ctx context.Context) (*UserAPIKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAPIKeyCreate) createSpec() (*UserAPIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAPIKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userapikey.Table, sqlgraph.NewFieldSpec(userapikey.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userapikey.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(userapikey.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(userapikey.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = value
	}
	if value, ok := _c.mutation.KeyEncrypted(); ok {
		_spec.SetField(userapikey.FieldKeyEncrypted, field.TypeString, value)
		_node.KeyEncrypted = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userapikey.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IssuedBy(); ok {
		_spec.SetField(userapikey.FieldIssuedBy, field.TypeString, value)
		_node.IssuedBy = &value
	}
	if value, ok := _c.mutation.IssuedByID(); ok {
		_spec.SetField(userapikey.FieldIssuedByID, field.TypeString, value)
		_node.IssuedByID = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userapikey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(userapikey.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(userapikey.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userapikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userapikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAPIKey.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAPIKeyUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAPIKeyCreate) OnConflict(opts ...sql.ConflictOption) *UserAPIKeyUpsertOne {
	_c.conflict = opts
	return &UserAPIKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAPIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAPIKeyCreate) OnConflictColumns(columns ...string) *UserAPIKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAPIKeyUpsertOne{
		create: _c,
	}
}

type (
	// UserAPIKeyUpsertOne is the builder for "upsert"-ing
	//  one UserAPIKey node.
	UserAPIKeyUpsertOne struct {
		create *UserAPIKeyCreate
	}

	// UserAPIKeyUpsert is the "OnConflict" setter.
	UserAPIKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserAPIKeyUpsert) SetUserID(v int64) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateUserID() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserAPIKeyUpsert) AddUserID(v int64) *UserAPIKeyUpsert {
	u.Add(userapikey.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UserAPIKeyUpsert) SetGroupID(v int64) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateGroupID() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *UserAPIKeyUpsert) AddGroupID(v int64) *UserAPIKeyUpsert {
	u.Add(userapikey.FieldGroupID, v)
	return u
}

// SetKeyHash sets the "key_hash" field.
func (u *UserAPIKeyUpsert) SetKeyHash(v string) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldKeyHash, v)
	return u
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateKeyHash() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldKeyHash)
	return u
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (u *UserAPIKeyUpsert) SetKeyEncrypted(v string) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldKeyEncrypted, v)
	return u
}

// UpdateKeyEncrypted sets the "key_encrypted" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateKeyEncrypted() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldKeyEncrypted)
	return u
}

// ClearKeyEncrypted clears the value of the "key_encrypted" field.
func (u *UserAPIKeyUpsert) ClearKeyEncrypted() *UserAPIKeyUpsert {
	u.SetNull(userapikey.FieldKeyEncrypted)
	return u
}

// SetStatus sets the "status" field.
func (u *UserAPIKeyUpsert) SetStatus(v string) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateStatus() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldStatus)
	return u
}

// SetIssuedBy sets the "issued_by" field.
func (u *UserAPIKeyUpsert) SetIssuedBy(v string) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldIssuedBy, v)
	return u
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateIssuedBy() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldIssuedBy)
	return u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *UserAPIKeyUpsert) ClearIssuedBy() *UserAPIKeyUpsert {
	u.SetNull(userapikey.FieldIssuedBy)
	return u
}

// SetIssuedByID sets the "issued_by_id" field.
func (u *UserAPIKeyUpsert) SetIssuedByID(v string) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldIssuedByID, v)
	return u
}

// UpdateIssuedByID sets the "issued_by_id" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateIssuedByID() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldIssuedByID)
	return u
}

// ClearIssuedByID clears the value of the "issued_by_id" field.
func (u *UserAPIKeyUpsert) ClearIssuedByID() *UserAPIKeyUpsert {
	u.SetNull(userapikey.FieldIssuedByID)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserAPIKeyUpsert) SetExpiresAt(v time.Time) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateExpiresAt() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserAPIKeyUpsert) ClearExpiresAt() *UserAPIKeyUpsert {
	u.SetNull(userapikey.FieldExpiresAt)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *UserAPIKeyUpsert) SetLastUsedAt(v time.Time) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateLastUsedAt() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *UserAPIKeyUpsert) ClearLastUsedAt() *UserAPIKeyUpsert {
	u.SetNull(userapikey.FieldLastUsedAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *UserAPIKeyUpsert) SetNotes(v string) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateNotes() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *UserAPIKeyUpsert) ClearNotes() *UserAPIKeyUpsert {
	u.SetNull(userapikey.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAPIKeyUpsert) SetUpdatedAt(v time.Time) *UserAPIKeyUpsert {
	u.Set(userapikey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAPIKeyUpsert) UpdateUpdatedAt() *UserAPIKeyUpsert {
	u.SetExcluded(userapikey.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserAPIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAPIKeyUpsertOne) UpdateNewValues() *UserAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userapikey.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAPIKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserAPIKeyUpsertOne) Ignore() *UserAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAPIKeyUpsertOne) DoNothing() *UserAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAPIKeyCreate.OnConflict
// documentation for more info.
func (u *UserAPIKeyUpsertOne) Update(set func(*UserAPIKeyUpsert)) *UserAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAPIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserAPIKeyUpsertOne) SetUserID(v int64) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserAPIKeyUpsertOne) AddUserID(v int64) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateUserID() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserAPIKeyUpsertOne) SetGroupID(v int64) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserAPIKeyUpsertOne) AddGroupID(v int64) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateGroupID() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateGroupID()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *UserAPIKeyUpsertOne) SetKeyHash(v string) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateKeyHash() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateKeyHash()
	})
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (u *UserAPIKeyUpsertOne) SetKeyEncrypted(v string) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetKeyEncrypted(v)
	})
}

// UpdateKeyEncrypted sets the "key_encrypted" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateKeyEncrypted() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateKeyEncrypted()
	})
}

// ClearKeyEncrypted clears the value of the "key_encrypted" field.
func (u *UserAPIKeyUpsertOne) ClearKeyEncrypted() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearKeyEncrypted()
	})
}

// SetStatus sets the "status" field.
func (u *UserAPIKeyUpsertOne) SetStatus(v string) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateStatus() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetIssuedBy sets the "issued_by" field.
func (u *UserAPIKeyUpsertOne) SetIssuedBy(v string) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetIssuedBy(v)
	})
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateIssuedBy() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateIssuedBy()
	})
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *UserAPIKeyUpsertOne) ClearIssuedBy() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearIssuedBy()
	})
}

// SetIssuedByID sets the "issued_by_id" field.
func (u *UserAPIKeyUpsertOne) SetIssuedByID(v string) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetIssuedByID(v)
	})
}

// UpdateIssuedByID sets the "issued_by_id" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateIssuedByID() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateIssuedByID()
	})
}

// ClearIssuedByID clears the value of the "issued_by_id" field.
func (u *UserAPIKeyUpsertOne) ClearIssuedByID() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearIssuedByID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserAPIKeyUpsertOne) SetExpiresAt(v time.Time) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateExpiresAt() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserAPIKeyUpsertOne) ClearExpiresAt() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *UserAPIKeyUpsertOne) SetLastUsedAt(v time.Time) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateLastUsedAt() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *UserAPIKeyUpsertOne) ClearLastUsedAt() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *UserAPIKeyUpsertOne) SetNotes(v string) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateNotes() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserAPIKeyUpsertOne) ClearNotes() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAPIKeyUpsertOne) SetUpdatedAt(v time.Time) *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAPIKeyUpsertOne) UpdateUpdatedAt() *UserAPIKeyUpsertOne {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserAPIKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAPIKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAPIKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserAPIKeyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserAPIKeyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserAPIKeyCreateBulk is the builder for creating many UserAPIKey entities in bulk.
type UserAPIKeyCreateBulk struct {
	config
	err      error
	builders []*UserAPIKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the UserAPIKey entities in the database.
func (_c *UserAPIKeyCreateBulk) Save(ctx context.Context) ([]*UserAPIKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAPIKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAPIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAPIKeyCreateBulk) SaveX(ctx context.Context) []*UserAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAPIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAPIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAPIKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAPIKeyUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAPIKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserAPIKeyUpsertBulk {
	_c.conflict = opts
	return &UserAPIKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAPIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAPIKeyCreateBulk) OnConflictColumns(columns ...string) *UserAPIKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAPIKeyUpsertBulk{
		create: _c,
	}
}

// UserAPIKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of UserAPIKey nodes.
type UserAPIKeyUpsertBulk struct {
	create *UserAPIKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserAPIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAPIKeyUpsertBulk) UpdateNewValues() *UserAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userapikey.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAPIKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserAPIKeyUpsertBulk) Ignore() *UserAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAPIKeyUpsertBulk) DoNothing() *UserAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAPIKeyCreateBulk.OnConflict
// documentation for more info.
func (u *UserAPIKeyUpsertBulk) Update(set func(*UserAPIKeyUpsert)) *UserAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAPIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserAPIKeyUpsertBulk) SetUserID(v int64) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserAPIKeyUpsertBulk) AddUserID(v int64) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateUserID() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserAPIKeyUpsertBulk) SetGroupID(v int64) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserAPIKeyUpsertBulk) AddGroupID(v int64) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateGroupID() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateGroupID()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *UserAPIKeyUpsertBulk) SetKeyHash(v string) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateKeyHash() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateKeyHash()
	})
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (u *UserAPIKeyUpsertBulk) SetKeyEncrypted(v string) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetKeyEncrypted(v)
	})
}

// UpdateKeyEncrypted sets the "key_encrypted" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateKeyEncrypted() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateKeyEncrypted()
	})
}

// ClearKeyEncrypted clears the value of the "key_encrypted" field.
func (u *UserAPIKeyUpsertBulk) ClearKeyEncrypted() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearKeyEncrypted()
	})
}

// SetStatus sets the "status" field.
func (u *UserAPIKeyUpsertBulk) SetStatus(v string) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateStatus() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetIssuedBy sets the "issued_by" field.
func (u *UserAPIKeyUpsertBulk) SetIssuedBy(v string) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetIssuedBy(v)
	})
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateIssuedBy() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateIssuedBy()
	})
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *UserAPIKeyUpsertBulk) ClearIssuedBy() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearIssuedBy()
	})
}

// SetIssuedByID sets the "issued_by_id" field.
func (u *UserAPIKeyUpsertBulk) SetIssuedByID(v string) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetIssuedByID(v)
	})
}

// UpdateIssuedByID sets the "issued_by_id" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateIssuedByID() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateIssuedByID()
	})
}

// ClearIssuedByID clears the value of the "issued_by_id" field.
func (u *UserAPIKeyUpsertBulk) ClearIssuedByID() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearIssuedByID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserAPIKeyUpsertBulk) SetExpiresAt(v time.Time) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateExpiresAt() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserAPIKeyUpsertBulk) ClearExpiresAt() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *UserAPIKeyUpsertBulk) SetLastUsedAt(v time.Time) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateLastUsedAt() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *UserAPIKeyUpsertBulk) ClearLastUsedAt() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *UserAPIKeyUpsertBulk) SetNotes(v string) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateNotes() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserAPIKeyUpsertBulk) ClearNotes() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAPIKeyUpsertBulk) SetUpdatedAt(v time.Time) *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAPIKeyUpsertBulk) UpdateUpdatedAt() *UserAPIKeyUpsertBulk {
	return u.Update(func(s *UserAPIKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserAPIKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserAPIKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAPIKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAPIKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
