// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/userapikey"
)

// UserAPIKey is the model entity for the UserAPIKey schema.
type UserAPIKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 关联 users.id
	UserID int64 `json:"user_id,omitempty"`
	// 关联 account_groups.id（订阅 group）
	GroupID int64 `json:"group_id,omitempty"`
	// bcrypt(plaintext_api_key)，慢哈希用于查重
	KeyHash string `json:"key_hash,omitempty"`
	// AES-256-GCM(plaintext)，可解密用于审计/迁移
	KeyEncrypted *string `json:"key_encrypted,omitempty"`
	// active / revoked / expired
	Status string `json:"status,omitempty"`
	// distributor / console / redeem
	IssuedBy *string `json:"issued_by,omitempty"`
	// distributor_id 或 admin_id
	IssuedByID *string `json:"issued_by_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAPIKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userapikey.FieldID, userapikey.FieldUserID, userapikey.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case userapikey.FieldKeyHash, userapikey.FieldKeyEncrypted, userapikey.FieldStatus, userapikey.FieldIssuedBy, userapikey.FieldIssuedByID, userapikey.FieldNotes:
			values[i] = new(sql.NullString)
		case userapikey.FieldExpiresAt, userapikey.FieldLastUsedAt, userapikey.FieldCreatedAt, userapikey.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAPIKey fields.
func (_m *UserAPIKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userapikey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userapikey.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userapikey.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case userapikey.FieldKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_hash", values[i])
			} else if value.Valid {
				_m.KeyHash = value.String
			}
		case userapikey.FieldKeyEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_encrypted", values[i])
			} else if value.Valid {
				_m.KeyEncrypted = new(string)
				*_m.KeyEncrypted = value.String
			}
		case userapikey.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case userapikey.FieldIssuedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issued_by", values[i])
			} else if value.Valid {
				_m.IssuedBy = new(string)
				*_m.IssuedBy = value.String
			}
		case userapikey.FieldIssuedByID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issued_by_id", values[i])
			} else if value.Valid {
				_m.IssuedByID = new(string)
				*_m.IssuedByID = value.String
			}
		case userapikey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case userapikey.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case userapikey.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case userapikey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userapikey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAPIKey.
// This includes values selected through modifiers, order, etc.
func (_m *UserAPIKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserAPIKey.
// Note that you need to call UserAPIKey.Unwrap() before calling this method if this UserAPIKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserAPIKey) Update() *UserAPIKeyUpdateOne {
	return NewUserAPIKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserAPIKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserAPIKey) Unwrap() *UserAPIKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAPIKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserAPIKey) String() string {
	var builder strings.Builder
	builder.WriteString("UserAPIKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("key_hash=")
	builder.WriteString(_m.KeyHash)
	builder.WriteString(", ")
	if v := _m.KeyEncrypted; v != nil {
		builder.WriteString("key_encrypted=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.IssuedBy; v != nil {
		builder.WriteString("issued_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IssuedByID; v != nil {
		builder.WriteString("issued_by_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserAPIKeys is a parsable slice of UserAPIKey.
type UserAPIKeys []*UserAPIKey
