// Code generated by ent, DO NOT EDIT.

package userapikey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldGroupID, v))
}

// KeyHash applies equality check predicate on the "key_hash" field. It's identical to KeyHashEQ.
func KeyHash(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldKeyHash, v))
}

// KeyEncrypted applies equality check predicate on the "key_encrypted" field. It's identical to KeyEncryptedEQ.
func KeyEncrypted(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldKeyEncrypted, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldStatus, v))
}

// IssuedBy applies equality check predicate on the "issued_by" field. It's identical to IssuedByEQ.
func IssuedBy(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldIssuedBy, v))
}

// IssuedByID applies equality check predicate on the "issued_by_id" field. It's identical to IssuedByIDEQ.
func IssuedByID(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldIssuedByID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldGroupID, v))
}

// KeyHashEQ applies the EQ predicate on the "key_hash" field.
func KeyHashEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldKeyHash, v))
}

// KeyHashNEQ applies the NEQ predicate on the "key_hash" field.
func KeyHashNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldKeyHash, v))
}

// KeyHashIn applies the In predicate on the "key_hash" field.
func KeyHashIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldKeyHash, vs...))
}

// KeyHashNotIn applies the NotIn predicate on the "key_hash" field.
func KeyHashNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldKeyHash, vs...))
}

// KeyHashGT applies the GT predicate on the "key_hash" field.
func KeyHashGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldKeyHash, v))
}

// KeyHashGTE applies the GTE predicate on the "key_hash" field.
func KeyHashGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldKeyHash, v))
}

// KeyHashLT applies the LT predicate on the "key_hash" field.
func KeyHashLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldKeyHash, v))
}

// KeyHashLTE applies the LTE predicate on the "key_hash" field.
func KeyHashLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldKeyHash, v))
}

// KeyHashContains applies the Contains predicate on the "key_hash" field.
func KeyHashContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldKeyHash, v))
}

// KeyHashHasPrefix applies the HasPrefix predicate on the "key_hash" field.
func KeyHashHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldKeyHash, v))
}

// KeyHashHasSuffix applies the HasSuffix predicate on the "key_hash" field.
func KeyHashHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldKeyHash, v))
}

// KeyHashEqualFold applies the EqualFold predicate on the "key_hash" field.
func KeyHashEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldKeyHash, v))
}

// KeyHashContainsFold applies the ContainsFold predicate on the "key_hash" field.
func KeyHashContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldKeyHash, v))
}

// KeyEncryptedEQ applies the EQ predicate on the "key_encrypted" field.
func KeyEncryptedEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldKeyEncrypted, v))
}

// KeyEncryptedNEQ applies the NEQ predicate on the "key_encrypted" field.
func KeyEncryptedNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldKeyEncrypted, v))
}

// KeyEncryptedIn applies the In predicate on the "key_encrypted" field.
func KeyEncryptedIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldKeyEncrypted, vs...))
}

// KeyEncryptedNotIn applies the NotIn predicate on the "key_encrypted" field.
func KeyEncryptedNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldKeyEncrypted, vs...))
}

// KeyEncryptedGT applies the GT predicate on the "key_encrypted" field.
func KeyEncryptedGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldKeyEncrypted, v))
}

// KeyEncryptedGTE applies the GTE predicate on the "key_encrypted" field.
func KeyEncryptedGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldKeyEncrypted, v))
}

// KeyEncryptedLT applies the LT predicate on the "key_encrypted" field.
func KeyEncryptedLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldKeyEncrypted, v))
}

// KeyEncryptedLTE applies the LTE predicate on the "key_encrypted" field.
func KeyEncryptedLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldKeyEncrypted, v))
}

// KeyEncryptedContains applies the Contains predicate on the "key_encrypted" field.
func KeyEncryptedContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldKeyEncrypted, v))
}

// KeyEncryptedHasPrefix applies the HasPrefix predicate on the "key_encrypted" field.
func KeyEncryptedHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldKeyEncrypted, v))
}

// KeyEncryptedHasSuffix applies the HasSuffix predicate on the "key_encrypted" field.
func KeyEncryptedHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldKeyEncrypted, v))
}

// KeyEncryptedIsNil applies the IsNil predicate on the "key_encrypted" field.
func KeyEncryptedIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldKeyEncrypted))
}

// KeyEncryptedNotNil applies the NotNil predicate on the "key_encrypted" field.
func KeyEncryptedNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldKeyEncrypted))
}

// KeyEncryptedEqualFold applies the EqualFold predicate on the "key_encrypted" field.
func KeyEncryptedEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldKeyEncrypted, v))
}

// KeyEncryptedContainsFold applies the ContainsFold predicate on the "key_encrypted" field.
func KeyEncryptedContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldKeyEncrypted, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldStatus, v))
}

// IssuedByEQ applies the EQ predicate on the "issued_by" field.
func IssuedByEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldIssuedBy, v))
}

// IssuedByNEQ applies the NEQ predicate on the "issued_by" field.
func IssuedByNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldIssuedBy, v))
}

// IssuedByIn applies the In predicate on the "issued_by" field.
func IssuedByIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldIssuedBy, vs...))
}

// IssuedByNotIn applies the NotIn predicate on the "issued_by" field.
func IssuedByNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldIssuedBy, vs...))
}

// IssuedByGT applies the GT predicate on the "issued_by" field.
func IssuedByGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldIssuedBy, v))
}

// IssuedByGTE applies the GTE predicate on the "issued_by" field.
func IssuedByGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldIssuedBy, v))
}

// IssuedByLT applies the LT predicate on the "issued_by" field.
func IssuedByLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldIssuedBy, v))
}

// IssuedByLTE applies the LTE predicate on the "issued_by" field.
func IssuedByLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldIssuedBy, v))
}

// IssuedByContains applies the Contains predicate on the "issued_by" field.
func IssuedByContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldIssuedBy, v))
}

// IssuedByHasPrefix applies the HasPrefix predicate on the "issued_by" field.
func IssuedByHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldIssuedBy, v))
}

// IssuedByHasSuffix applies the HasSuffix predicate on the "issued_by" field.
func IssuedByHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldIssuedBy, v))
}

// IssuedByIsNil applies the IsNil predicate on the "issued_by" field.
func IssuedByIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldIssuedBy))
}

// IssuedByNotNil applies the NotNil predicate on the "issued_by" field.
func IssuedByNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldIssuedBy))
}

// IssuedByEqualFold applies the EqualFold predicate on the "issued_by" field.
func IssuedByEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldIssuedBy, v))
}

// IssuedByContainsFold applies the ContainsFold predicate on the "issued_by" field.
func IssuedByContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldIssuedBy, v))
}

// IssuedByIDEQ applies the EQ predicate on the "issued_by_id" field.
func IssuedByIDEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldIssuedByID, v))
}

// IssuedByIDNEQ applies the NEQ predicate on the "issued_by_id" field.
func IssuedByIDNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldIssuedByID, v))
}

// IssuedByIDIn applies the In predicate on the "issued_by_id" field.
func IssuedByIDIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldIssuedByID, vs...))
}

// IssuedByIDNotIn applies the NotIn predicate on the "issued_by_id" field.
func IssuedByIDNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldIssuedByID, vs...))
}

// IssuedByIDGT applies the GT predicate on the "issued_by_id" field.
func IssuedByIDGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldIssuedByID, v))
}

// IssuedByIDGTE applies the GTE predicate on the "issued_by_id" field.
func IssuedByIDGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldIssuedByID, v))
}

// IssuedByIDLT applies the LT predicate on the "issued_by_id" field.
func IssuedByIDLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldIssuedByID, v))
}

// IssuedByIDLTE applies the LTE predicate on the "issued_by_id" field.
func IssuedByIDLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldIssuedByID, v))
}

// IssuedByIDContains applies the Contains predicate on the "issued_by_id" field.
func IssuedByIDContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldIssuedByID, v))
}

// IssuedByIDHasPrefix applies the HasPrefix predicate on the "issued_by_id" field.
func IssuedByIDHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldIssuedByID, v))
}

// IssuedByIDHasSuffix applies the HasSuffix predicate on the "issued_by_id" field.
func IssuedByIDHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldIssuedByID, v))
}

// IssuedByIDIsNil applies the IsNil predicate on the "issued_by_id" field.
func IssuedByIDIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldIssuedByID))
}

// IssuedByIDNotNil applies the NotNil predicate on the "issued_by_id" field.
func IssuedByIDNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldIssuedByID))
}

// IssuedByIDEqualFold applies the EqualFold predicate on the "issued_by_id" field.
func IssuedByIDEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldIssuedByID, v))
}

// IssuedByIDContainsFold applies the ContainsFold predicate on the "issued_by_id" field.
func IssuedByIDContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldIssuedByID, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldExpiresAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldLastUsedAt))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAPIKey) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAPIKey) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAPIKey) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.NotPredicates(p))
}
