// Code generated by ent, DO NOT EDIT.

package distributorbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLTE(FieldID, id))
}

// DistributorID applies equality check predicate on the "distributor_id" field. It's identical to DistributorIDEQ.
func DistributorID(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldDistributorID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldName, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldTokenHash, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldEnabled, v))
}

// ContactEmail applies equality check predicate on the "contact_email" field. It's identical to ContactEmailEQ.
func ContactEmail(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldContactEmail, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldNotes, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// DistributorIDEQ applies the EQ predicate on the "distributor_id" field.
func DistributorIDEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldDistributorID, v))
}

// DistributorIDNEQ applies the NEQ predicate on the "distributor_id" field.
func DistributorIDNEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldDistributorID, v))
}

// DistributorIDIn applies the In predicate on the "distributor_id" field.
func DistributorIDIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIn(FieldDistributorID, vs...))
}

// DistributorIDNotIn applies the NotIn predicate on the "distributor_id" field.
func DistributorIDNotIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotIn(FieldDistributorID, vs...))
}

// DistributorIDGT applies the GT predicate on the "distributor_id" field.
func DistributorIDGT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGT(FieldDistributorID, v))
}

// DistributorIDGTE applies the GTE predicate on the "distributor_id" field.
func DistributorIDGTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGTE(FieldDistributorID, v))
}

// DistributorIDLT applies the LT predicate on the "distributor_id" field.
func DistributorIDLT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLT(FieldDistributorID, v))
}

// DistributorIDLTE applies the LTE predicate on the "distributor_id" field.
func DistributorIDLTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLTE(FieldDistributorID, v))
}

// DistributorIDContains applies the Contains predicate on the "distributor_id" field.
func DistributorIDContains(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContains(FieldDistributorID, v))
}

// DistributorIDHasPrefix applies the HasPrefix predicate on the "distributor_id" field.
func DistributorIDHasPrefix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasPrefix(FieldDistributorID, v))
}

// DistributorIDHasSuffix applies the HasSuffix predicate on the "distributor_id" field.
func DistributorIDHasSuffix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasSuffix(FieldDistributorID, v))
}

// DistributorIDEqualFold applies the EqualFold predicate on the "distributor_id" field.
func DistributorIDEqualFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEqualFold(FieldDistributorID, v))
}

// DistributorIDContainsFold applies the ContainsFold predicate on the "distributor_id" field.
func DistributorIDContainsFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContainsFold(FieldDistributorID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContainsFold(FieldName, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContainsFold(FieldTokenHash, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldEnabled, v))
}

// ContactEmailEQ applies the EQ predicate on the "contact_email" field.
func ContactEmailEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldContactEmail, v))
}

// ContactEmailNEQ applies the NEQ predicate on the "contact_email" field.
func ContactEmailNEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldContactEmail, v))
}

// ContactEmailIn applies the In predicate on the "contact_email" field.
func ContactEmailIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIn(FieldContactEmail, vs...))
}

// ContactEmailNotIn applies the NotIn predicate on the "contact_email" field.
func ContactEmailNotIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotIn(FieldContactEmail, vs...))
}

// ContactEmailGT applies the GT predicate on the "contact_email" field.
func ContactEmailGT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGT(FieldContactEmail, v))
}

// ContactEmailGTE applies the GTE predicate on the "contact_email" field.
func ContactEmailGTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGTE(FieldContactEmail, v))
}

// ContactEmailLT applies the LT predicate on the "contact_email" field.
func ContactEmailLT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLT(FieldContactEmail, v))
}

// ContactEmailLTE applies the LTE predicate on the "contact_email" field.
func ContactEmailLTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLTE(FieldContactEmail, v))
}

// ContactEmailContains applies the Contains predicate on the "contact_email" field.
func ContactEmailContains(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContains(FieldContactEmail, v))
}

// ContactEmailHasPrefix applies the HasPrefix predicate on the "contact_email" field.
func ContactEmailHasPrefix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasPrefix(FieldContactEmail, v))
}

// ContactEmailHasSuffix applies the HasSuffix predicate on the "contact_email" field.
func ContactEmailHasSuffix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasSuffix(FieldContactEmail, v))
}

// ContactEmailIsNil applies the IsNil predicate on the "contact_email" field.
func ContactEmailIsNil() predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIsNull(FieldContactEmail))
}

// ContactEmailNotNil applies the NotNil predicate on the "contact_email" field.
func ContactEmailNotNil() predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotNull(FieldContactEmail))
}

// ContactEmailEqualFold applies the EqualFold predicate on the "contact_email" field.
func ContactEmailEqualFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEqualFold(FieldContactEmail, v))
}

// ContactEmailContainsFold applies the ContainsFold predicate on the "contact_email" field.
func ContactEmailContainsFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContainsFold(FieldContactEmail, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldContainsFold(FieldNotes, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotNull(FieldExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DistributorBinding) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DistributorBinding) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DistributorBinding) predicate.DistributorBinding {
	return predicate.DistributorBinding(sql.NotPredicates(p))
}
